#!/usr/bin/perl

use strict;

our $TOOLHOME;
BEGIN {
	$0 =~ m"^(.*)/";
	$TOOLHOME = ` cd "$1/.." && pwd || echo . `;
	chomp $TOOLHOME;
}

use lib "$0.d/lib/perl5";
use NCRTAlertQueue;

use strict;
use Carp::Always;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

####

my $min = int( time / 60 ) % 5;

mkdir_or_die      "$WORKDIR/aq_event";
mkdir_or_die      "$WORKDIR/aq_active";
mkdir_or_die      "$WORKDIR/aq_inactive";
mkdir_or_die      "$WORKDIR/aq_web";
mkdir_or_die      "$WORKDIR/aq_mail";
mkdir_or_die      "$WORKDIR/aq_slack";
mkdir_or_die      "$WORKDIR/aq_graph";
system_or_die     "$0.d/bin/eventq   update  $CONFDIR $WORKDIR";
system_or_die     "$0.d/bin/session  open    $CONFDIR $WORKDIR";
run_as_background "$0.d/bin/web      open    $CONFDIR $WORKDIR";
#run_as_background "$0.d/bin/mail     open    $CONFDIR $WORKDIR";
#run_as_background "$0.d/bin/slack    open    $CONFDIR $WORKDIR";
#system_or_die     "$0.d/bin/session  rename  $CONFDIR $WORKDIR" if $min == 1;
#run_as_background "$0.d/bin/web      rename  $CONFDIR $WORKDIR" if $min == 1;
#run_as_background "$0.d/bin/slack    rename  $CONFDIR $WORKDIR" if $min == 1;
system_or_die     "$0.d/bin/session  close   $CONFDIR $WORKDIR" if $min == 2;
run_as_background "$0.d/bin/web      close   $CONFDIR $WORKDIR" if $min == 2;
#run_as_background "$0.d/bin/mail     close   $CONFDIR $WORKDIR" if $min == 2;
#run_as_background "$0.d/bin/slack    close   $CONFDIR $WORKDIR" if $min == 2;
system_or_die     "$0.d/bin/eventq   cleanup $CONFDIR $WORKDIR" if $min == 3;
system_or_die     "$0.d/bin/session  cleanup $CONFDIR $WORKDIR" if $min == 3;
run_as_background "$0.d/bin/web      cleanup $CONFDIR $WORKDIR" if $min == 3;
run_as_background "$0.d/bin/web      update  $CONFDIR $WORKDIR" if $min == 4;
exit 0;


