#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
if( open my $f, '<', "$CONFDIR/ncrtbuild.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		die unless m"^(\w+)=(.*)$";
		$ncrtconf{$1} = $2;
	}
	close $f;
}

#### load linuxhost conf.
my %targets;
if( open my $f, '<', "$CONFDIR/linuxhost.targets" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		die unless m"^([-.\w]+)$";
		$targets{$1} = 1;
	}
	close $f;
}

#### append detector info.
if( open my $f, '>>', "$WORKDIR/detectors" ){
	print $f "linuxhost_osperf	display_name=\"OS Performance\"\n";
	close $f;
}

#### append detector mapping
if( open my $f, '>>', "$WORKDIR/ncrtagent_host2service" ){
	foreach my $i ( keys %targets ){
		print $f "$i/linuxhost\tlinuxhost_osperf\n";
	}
	close $f;
}


