#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
my $f = "$CONFDIR/ncrtbuild.conf";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	die unless m"^(\w+)=(.*)$";
	$ncrtconf{$1} = $2;
}
close $h;

#### load linux conf.
my %targets;
my $f = "$CONFDIR/agent/linux.hosts";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	die unless m"^([-.\w]+)$";
	$targets{$1} = 1;
}
close $h;

#### append hosts info.
my $f = "$WORKDIR/hosts";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
while( my ($k, $v) = each %targets ){
	print $h "$k	linux\n";
}
close $h;

#### append hosttype info.
my $f = "$WORKDIR/hosttypes";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "linux	display_name=Linux:%hostname% address=%hostname%\n";
close $h;


