#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
if( open my $f, '<', "$CONFDIR/ncrtbuild.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		die unless m"^(\w+)=(.*)$";
		$ncrtconf{$1} = $2;
	}
	close $f;
}

#### load ncrt agents conf.
my @ncrtagents;
if( open my $f, '<', "$CONFDIR/ncrtagents.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		push @ncrtagents, $_;
	}
	close $f;
}

#### load linuxhost conf.
my @linuxhosts;
if( open my $f, '<', "$CONFDIR/linuxhost.targets" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		push @linuxhosts, $_;
	}
	close $f;
}

#### load detector conf.
my @categories;
my $f = "$CONFDIR/linuxhost_proc.categories";
if( open my $h, '<', $f ){
	while( <$h> ){
		chomp;
		next if m"^\s*(#|$)";
		die "$f:$.:$_: illegal format, stopped" unless m"^(\S+)\s+(\S+)\s+(\S+)$";
		push @categories, [$1, $2, $3];
	}
	close $h;
}
foreach my $hostname ( @linuxhosts ){
	if( open my $h, '>', "$WORKDIR/ncrtagent/$hostname/linuxhost_proc.categories" ){
		foreach my $c ( @categories ){
			my $category = $c->[0];
			my $user_re = $c->[1];
			my $args_re = $c->[2];
			print $h "$category $user_re $args_re\n";
		}
		close $h;
	}
}

#### append detector info.
if( open my $h, '>>', "$WORKDIR/detectors" ){
	print $h "linuxhost_proc	display_name=\"Process\"\n";
	close $h;
}

#### append detector mapping
if( open my $h, '>>', "$WORKDIR/ncrtagent_host2service" ){
	foreach my $i ( @linuxhosts ){
		print $h "$i/linuxhost\tlinuxhost_proc\n";
	}
	close $h;
}




