#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
my $f = "$CONFDIR/ncrtbuild.conf";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	die unless m"^(\w+)=(.*)$";
	$ncrtconf{$1} = $2;
}
close $h;

#### load service conf.
my %vhost2vservices;
my $f = "$CONFDIR/composite/procedure.conf";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	if( m"^===\s+(\S+)\s+(\S+)\s+<\s+(\S+(\s+\S+)*)\s+===$" ){
		my $vhost = $1;
		my $vservice = $2;
		$vhost2vservices{$vhost}->{$vservice} = 1;
	}
}
close $h;

#### append service info.
my $f = "$WORKDIR/services";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "procedure	composite\n";
close $h;

#### append conf info.
my $f = "$WORKDIR/service2conf";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "procedure	composite/procedure.conf\n";
close $h;

#### append service mapping
my $f = "$WORKDIR/host2service";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};

while( my ($vhost, $vservices) = each %vhost2vservices ){
	foreach my $vservice ( sort keys %$vservices ){
		print $h "$vhost	procedure,$vservice\n";
	}
}
close $h;

