#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### append conf info.
my $f = "$WORKDIR/plugin2type2pluginconf2format";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "alertqueue	reporter	alertqueue.conf			simple\n";
print $h "alertqueue	reporter	alertqueue.alertrules		simple\n";
print $h "alertqueue	reporter	alertqueue.reportrules		simple\n";
print $h "alertqueue	reporter	alertqueue_mail.tt		simple\n";
print $h "alertqueue	reporter	alertqueue_web.tt		simple\n";
print $h "alertqueue	reporter	alertqueue_slack.tt		simple\n";
close $h;

exit 0;
