#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
my $f = "$CONFDIR/ncrtbuild.conf";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	die unless m"^(\w+)=(.*)$";
	$ncrtconf{$1} = $2;
}
close $h;

#### load linux conf.
my %targets;
my %default = (
	listen_address => "0.0.0.0",
	listen_port => 46848,
	daemon_user => "ncrtagent",
	timeout => 60,
	agent_protocol => 'ncrtagent',
	agent_address => undef,
	agent_port => 46848,
);
my $f = "$CONFDIR/agenttype/linux.hosts";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	die unless m"^(\*|[-.\w]+)((\s+\w+=\S*)*)$";
	my $host = $1;
	my %param;
	foreach my $kv ( split m"\s+", $2 ){
		next unless $kv =~ m"^(\w+)=(.*)$";
		$param{$1} = $2;
	}

	if( $host eq "*" ){
		%default = %param;
	}else{
		$targets{$host} = { %default, %param };
	}
}
close $h;

#### append hosts info.
my $f = "$WORKDIR/agenthosts";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
while( my ($k, $v) = each %targets ){
	my @param;
	while( my ($k, $v) = each %$v ){
		push @param, "$k=$v";
	}
	print $h "$k	linux	", join("\t", @param), "\n";
}
close $h;

#### append agenttype info.
my $f = "$WORKDIR/agenttypes";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "linux	display_name=Linux:<hostname> address=<hostname> check_command=ncrtmaster_ping\n";
close $h;

#### generate ncrtagent.conf

