#!/usr/bin/perl

use strict;

if( @ARGV < 4 ){
	print "usage: % $0 PLUGINCONFDIR PLUGINWORKDIR DISTRIBUTEDDIR PLAYBOOKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];
our $DISTRIBUTEDDIR = $ARGV[2];
our $PLAYBOOKDIR = $ARGV[3];

#### functions.

sub system_or_die ($) {
	my ($cmd) = @_;
	my $r = system $cmd;
	if   ($? == -1){
		die sprintf "%s: failed to execute: %d, stopped",
			$cmd, $!;
	}elsif($? & 127){
		die sprintf
			"%s: child died with signal %d, %s coredump, stopped",
			$cmd, ($? & 127), ($? & 128) ? 'with' : 'without';
	}elsif( ($?>>8) != 0){
		 die sprintf "%s: child exited with value %d, stopped",
			$cmd, $? >> 8;
	}
}

#### load docker conf.
my %targets;
my %default = (
);
my $f = "$CONFDIR/mastertype/docker.hosts";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	die unless m"^(\*|[-.\w]+)((\s+\w+=\S*)*)$";
	my $host = $1;
	my %param;
	foreach my $kv ( split m"\s+", $2 ){
		next unless $kv =~ m"^(\w+)=(.*)$";
		$param{$1} = $2;
	}

	if( $host eq "*" ){
		%default = %param;
	}else{
		$targets{$host} = { %default, %param };
	}
}
close $h;

my %server_settings = (
	'GRAFANA_DATAOWNER'		=> 'ncrt_gfuser',
	'GRAFANA_DATAOWNERPASSWD'	=> 'XXXXSECRETXXXX',
	'GRAFANA_DATAOWNEREMAIL'	=> 'ncrt_gfuser@example.com',

	'GRAFANA_LOCALPORT'		=> '3000',
	'INFLUXDB_LOCALPORT'		=> '8086',

	'BROWSERSIDE_URL_PREFIX'	=> 'http://example.com/',
	'SERVERSIDE_PATH_PREFIX'	=> '/',
	'SERVERSIDE_PORT'		=> '80',
	'PROXY'				=> '',

	'SYSLOG_SERVER' => '',
	'LANG' => 'C',
	'TZ' => 'GMT',
	'MTU' => '',
);
my %server_settings_which_must_be_specified_by_user = (
	'GRAFANA_DATAOWNEREMAIL'	=> 1,
	'GRAFANA_DATAOWNERPASSWD'	=> 1,
	'BROWSERSIDE_URL_PREFIX'	=> 1,
);

my $f = "$CONFDIR/mastertype/docker.conf";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	die "$f:$.: illegal format, stopped"  unless m"^(\w+)=(.*)$";
	die "$f:$.: unknown setting, stopped" unless exists $server_settings{$1};
	$server_settings{$1} = $2;
	delete $server_settings_which_must_be_specified_by_user{$1};
}
close $h;
if( %server_settings_which_must_be_specified_by_user ){
	my $s = join(" ", keys %server_settings_which_must_be_specified_by_user);
	die "$f: following settings must be specified: $s, stopped";
}

#### append masterhosts info.
my $f = "$WORKDIR/masterhosts";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
while( my ($k, $v) = each %targets ){
	my @param;
	while( my ($k, $v) = each %$v ){
		push @param, "$k=$v";
	}
	print $h "$k	docker	", join("\t", @param), "\n";
}
close $h;

#### append mastertype info.
my $f = "$WORKDIR/mastertypes";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "docker	\n";
close $h;

#### create master base directories.

while( my ($host, $params) = each %targets ){
	system_or_die "rsync -aJUSx $0.d/ $DISTRIBUTEDDIR/$host/";
}

#### append mastertype setting files
my $f = "$WORKDIR/plugin2type2pluginconf2format";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "docker	mastertype	docker.conf	simple\n";
close $h;


#### Playbooks typically cannot read setting files (KEY=VALUE format).
#### Plugin scripts may convert settings to YAML-formatted files.
#### You can place YAML-formatted configuration files in ncrtbuild working dir and name them "plugin_PLUGINNAME_XXX.yml" to prevent conflicts between each configuration file.

#### pass settings to the playbook of this plugin
my $f = "$PLAYBOOKDIR/plugin_mastertype_docker.vars.yml";
open my $h, '>', $f or do {
	die "$f: cannot open, stopped";
};
while( my ($k, $v) = each %server_settings ){
	print $h "  '$k' : '$v'\n";
}
close $h;

exit 0;

