#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
if( open my $f, '<', "$CONFDIR/ncrtbuild.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		die unless m"^(\w+)=(.*)$";
		$ncrtconf{$1} = $2;
	}
	close $f;
}

#### load ncrt masters conf.
my @ncrtmasters;
if( open my $f, '<', "$CONFDIR/ncrtmasters.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		push @ncrtmasters, $_;
	}
	close $f;
}

#### load service conf.
my $f = "$CONFDIR/gateway/ltsv.conf";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
my $vhost;
my $vservice;
my %vhost2vservice;
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	if( m"^===\s+(\S+)\s+(\S+)\s+===$" ){
		$vhost = $1;
		$vservice = $2;
	}elsif( m"^(\w+=\S*)$" ){
		#
	}elsif( m"^
		(\S+)\s+(/\S*)\s+(\S+)
	$"x ){
		my $host = $1;
		my $path = $2;
		my $fieldpattern = $3;
		$vhost2vservice{$vhost}->{$vservice} = 1;
	}else{
		die "$f:$.: illegal format, stopped";
	}
}
close $h;

#### append service info.
open my $h, '>>', "$WORKDIR/services" or do {
	die "$f: cannot open, stopped";
};
print $h "ltsv	gateway\n";
close $h;

#### append conf info.
open my $h, '>>', "$WORKDIR/service2conf" or do {
	die "$f: cannot open, stopped";
};
print $h "ltsv	gateway/ltsv.conf\n";
close $h;

#### append service mapping
open my $h, '>>', "$WORKDIR/host2service" or do {
	die "$f: cannot open, stopped";
};

while( my ($vhost, $vservices) = each %vhost2vservice ){
	my $index = '0000';
	foreach my $vservice ( sort keys %$vservices ){
		print $h "$vhost	ltsv.$index",
			"	display_name=\"$vservice\"\n";
		$index++;
	}
}
close $h;




