#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load hosts
my %host2service;
my $f = "$WORKDIR/monitoredhost2service2measurement";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	m"^(\S+)\s+(\w+)\s+(\w+)(\s|$)" or die "$f:$.: illegal format, stopped";
	my $host = $1;
	my $service = $2;
	my $measure = $3;
	push @{$host2service{$host}}, ($service || $measure);
}
close $h;

#### load contact conf.
my $teamname;
my %host2team;
my %team2user;
my %users;
my $f = "$CONFDIR/contact/hostmanagementteam.conf";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
my $teamname;
my $userprofilename;
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	die "$f:$.: illegal format, stopped" unless m"^\s*(?:
		team \s+ (?<teamname>\S+) |
		host \s+ (?<hostname>\S+) |
		user \s+ (?<username>[-\w]+) |
		profile_of_user \s+ (?<userprofilename>[-\w]+) |
		password \s+ (?<password>\S+)
	)\s*$"x;
	if    ( $+{teamname} ne "" ){
		$teamname = $+{teamname};
	}elsif( $+{hostname} ne "" ){
		push @{ $host2team{$+{hostname}} }, $teamname;
	}elsif( $+{username} ne "" ){
		push @{$team2user{$teamname}}, $+{username};
		$users{$+{username}} = {} unless exists $users{$+{username}};
	}elsif( $+{userprofilename} ne "" ){
		$userprofilename = $+{userprofilename};
	}elsif( $+{password} ne "" ){
		$users{$userprofilename}{password} = $+{password};
	}else{
		die "$f:$.: illegal format, stopped";
	}
}
close $h;

####
my $f = "$WORKDIR/monitoredhost2user";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
while( my ($host, $service) = each %host2service ){
	foreach my $teamname ( @{$host2team{$host}} ){
		my $users  = $team2user{$teamname}  // [];
		my $contacts = join ",", @$users;
		print $h "$host\t$contacts\n";
	}
}
close $h;

my $f = "$WORKDIR/monitoredhost2service2user";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
while( my ($host, $services) = each %host2service ){
	foreach my $service ( @$services ){
		foreach my $teamname ( @{$host2team{$host}} ){
			my $users  = $team2user{$teamname}  // [];
			my $contacts = join ",", @$users;
			print $h "$host\t$service\t$contacts\n";
		}
	}
}
close $h;

my $f = "$WORKDIR/monitoredhost2group";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
while( my ($host) = each %host2service ){
	foreach my $team ( @{$host2team{$host}} ){
		print $h "$host\t$team\n";
	}
}
close $h;

my $f = "$WORKDIR/monitoredhost2service2group";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
while( my ($host, $services) = each %host2service ){
	foreach my $service ( @$services ){
		foreach my $team ( @{$host2team{$host}} ){
			print $h "$host\t$service\t$team\n";
		}
	}
}
close $h;

my $f = "$WORKDIR/users";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
while( my ($user, $profiles) = each %users ){
	my @profiles;
	foreach my $k ( sort keys %$profiles ){
		my $v = $$profiles{$k};
		push @profiles, "$k=$v";
	}
	print $h "$user\t", join("\t", @profiles), "\n";
}
close $h;


