#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
if( open my $f, '<', "$CONFDIR/ncrtbuild.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		die unless m"^(\w+)=(.*)$";
		$ncrtconf{$1} = $2;
	}
	close $f;
}

#### load conf. for ncrt masters
my @ncrtmasters;
if( open my $f, '<', "$CONFDIR/ncrtmasters.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		push @ncrtmasters, $_;
	}
	close $f;
}

#### load conf. for ncrt agents
my @ncrtagents;
if( open my $f, '<', "$CONFDIR/ncrtagents.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		push @ncrtagents, $_;
	}
	close $f;
}

#### load conf. for linuxhosts
my @linuxhosts;
if( open my $f, '<', "$CONFDIR/linuxhost.targets" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		push @linuxhosts, $_;
	}
	close $f;
}

#### load conf. for networkserverperf
my @rules;
my $f = "$CONFDIR/linuxhost_networkserverperf.conf";
if( open my $h, '<', $f ){
	while( <$h> ){
		chomp;
		next if m"^\s*(#|$)";
		die "$f:$.: illegal format, stopped" unless m"^(\S+)\s+(\d+(?:,\d+)*)/(\w+)(?:\s+(\w+)\s+\[([-+]?\d+),([-+]?\d+)\])?$";
		my $hosts = qr"^$1$";
		my $ports = $2;
		my $proto = $3;
		my $severity = $4;
		my $lower = int $5;
		my $upper = int $6;
		die "$f:$.: unknown protocol, stopped" unless $proto =~ m"^(tcp|udp)$";
		die "$f:$.: unknown severity, stopped" unless $severity =~ m"^(warn|crit|)$";
		my @ports;
		foreach my $p (split m",", $ports){ push @ports, sprintf '%i/%s', $p, $proto; }
		foreach my $port ( @ports ){
			die "$f:$.: illegal port, stopped" if $port < 1 || $port > 65535;
			push @rules, [$hosts, $port, $severity, $lower, $upper];
		}
	}
	close $f;
}

#### append detector info.
if( open my $f, '>>', "$WORKDIR/detectors" ){
	print $f "linuxhost_networkserverperf	display_name=\"Network Server Connections\"\n";
	close $f;
}

#### append detector mapping
if( open my $f, '>>', "$WORKDIR/ncrtagent_host2service" ){
	foreach my $i ( @linuxhosts ){
		print $f "$i/linuxhost\tlinuxhost_networkserverperf\n";
	}
	close $f;
}


