#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
if( open my $f, '<', "$CONFDIR/ncrtbuild.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		die unless m"^(\w+)=(.*)$";
		$ncrtconf{$1} = $2;
	}
	close $f;
}

#### load hosts
my %host2service;
if( open my $f, '<', "$WORKDIR/host2service" ){
	while( <$f> ){
		chomp;
		my ($host, $service) = split m"\s+";
		push @{$host2service{$host}}, $service;
	}
	close $f;
}
if( open my $f, '<', "$WORKDIR/host2service" ){
	while( <$f> ){
		chomp;
		my ($host, $service) = split m"\s+";
		push @{$host2service{$host}}, $service;
	}
	close $f;
}

#### load contact conf.
my $teamname;
my %host2team;
my %team2email;
my %team2user;
my %emails;
my %users;
my $f = "$CONFDIR/contact_simple.conf";
if( open my $h, '<', $f ){
	my $teamname;
	while( <$h> ){
		chomp;
		next if m"^\s*(#|$)";
		die "$f:$.: illegal format, stopped" unless m"^\s*(?:
			(?<teamname>\S+): |
			\*\s*(?<hostname>\S+) |
			(?<email>\S+\@\S+) |
			(?<username>\w+)
		)\s*$"x;
		if( $+{teamname} ){
			$teamname = $+{teamname};
		}elsif( $+{hostname} ){
			push @{ $host2team{$+{hostname}} }, $teamname;
		}elsif( $+{email} ){
			push @{$team2email{$teamname}}, $+{email};
			$emails{$+{email}}++;
		}elsif( $+{username} ){
			push @{$team2user{$teamname}}, $+{username};
			$users{$+{username}}++;
		}else{
			die "$f:$.: illegal format, stopped";
		}
	}
	close $h;
}

####
my $f = "$WORKDIR/host2contact";
if( open my $h, '>>', $f ){
	while( my ($host, $service) = each %host2service ){
		foreach my $teamname ( @{$host2team{$host}} ){
			my $emails = $team2email{$teamname} // [];
			my $users  = $team2user{$teamname}  // [];
			my $contacts = join ",", @$emails, @$users;
			print $h "$host\t$contacts\n";
		}
	}
	close $h
}
my $f = "$WORKDIR/hostservice2contact";
if( open my $h, '>>', $f ){
	while( my ($host, $services) = each %host2service ){
		foreach my $service ( @$services ){
			foreach my $teamname ( @{$host2team{$host}} ){
				my $emails = $team2email{$teamname} // [];
				my $users  = $team2user{$teamname}  // [];
				my $contacts = join ",", @$emails, @$users;
				print $h "$host\t$service\t$contacts\n";
			}
		}
	}
	close $h
}
my $f = "$WORKDIR/host2group";
if( open my $h, '>>', $f ){
	while( my ($host) = each %host2service ){
		foreach my $team ( @{$host2team{$host}} ){
			print $h "$host\t$team\n";
		}
	}
	close $h;
}
my $f = "$WORKDIR/hostservice2group";
if( open my $h, '>>', $f ){
	while( my ($host, $services) = each %host2service ){
		foreach my $service ( @$services ){
			foreach my $team ( @{$host2team{$host}} ){
				print $h "$host\t$service\t$team\n";
			}
		}
	}
	close $h;
}
my $f = "$WORKDIR/users";
if( open my $h, '>>', $f ){
	while( my ($user) = each %users ){ print $h "$user\n"; }
	close $h;
}
my $f = "$WORKDIR/addresses";
if( open my $h, '>>', $f ){
	while( my ($email) = each %emails ){ print $h "$email\n"; }
	close $h;
}


