#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load linuxhosts.
my %targets;
my $f = "$WORKDIR/agenthosts";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	my ($host, $agenttype) = split m"\s+";
	next unless $agenttype =~ m"^(linux|macos)$";
	$targets{$host} = 1;
}
close $h;

#### append measure info.
my $f = "$WORKDIR/measurements";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "proc	agent	display_name=\"Process\"\n";
close $h;

#### append conf info.
my $f = "$WORKDIR/plugin2type2pluginconf2format";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "proc	agent	proc.categories		default\n";
print $h "proc	agent	proc_count.rules	default\n";
print $h "proc	agent	proc_elapsed.rules	default\n";
close $h;

#### append service mapping
my $f = "$WORKDIR/monitoredhost2service2measurement";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
foreach my $i ( keys %targets ){
	print $h "$i	proc	proc\n";
}
close $h;




