#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
my $f = "$CONFDIR/ncrtbuild.conf";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	die unless m"^(\w+)=(.*)$";
	$ncrtconf{$1} = $2;
}
close $h;

#### load linuxhosts.
my %targets;
my $f = "$WORKDIR/hosts";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	my ($host, $hosttype) = split m"\s+";
	next unless $hosttype =~ m"^(linux)$";
	$targets{$host} = 1;
}
close $h;

#### append service info.
my $f = "$WORKDIR/services";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "proc	agent	display_name=\"Process\"\n";
close $h;

#### append conf info.
my $f = "$WORKDIR/service2conf";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "proc	agent/proc.categories\n";
print $h "proc	agent/proc_count.rules\n";
print $h "proc	agent/proc_elapsed.rules\n";
close $h;

#### append service mapping
my $f = "$WORKDIR/host2service";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
foreach my $i ( keys %targets ){
	print $h "$i\tproc\n";
}
close $h;




