#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
my $f = "$CONFDIR/ncrtbuild.conf";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	die unless m"^(\w+)=(.*)$";
	$ncrtconf{$1} = $2;
}
close $h;

#### load windows conf.
my %targets;
my %default = (
	listen_address => "0.0.0.0",
	listen_port => 5666,
	daemon_user => "ncrtagent",
	timeout => 60,
	agent_protocol => 'nrpe',
	agent_address => undef,
	agent_port => 5666,
	ansible_connection => 'winrm',
	ansible_winrm_server_cert_validation => 'ignore'
);
my $f = "$CONFDIR/agenttype_windows.hosts";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
while( <$h> ){
	chomp;
	next if m"^\s*(#|$)";
	die unless m"^(\*|[-.\w]+)((\s+\w+=\S*)*)$";
	my $host = $1;
	my %param;
	foreach my $kv ( split m"\s+", $2 ){
		next unless $kv =~ m"^(\w+)=(.*)$";
		$param{$1} = $2;
	}

	if( $host eq "*" ){
		%default = (%default, %param);
	}else{
		$targets{$host} = { %default, %param };
	}
}
close $h;

#### append hosts info.
my $f = "$WORKDIR/hosts";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
while( my ($k, $v) = each %targets ){
	my @param;
	while( my ($k, $v) = each %$v ){
		push @param, "$k=$v";
	}
	print $h "$k	windows	", join("\t", @param), "\n";
}
close $h;

#### append agenttype info.
my $f = "$WORKDIR/agenttypes";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "windows	display_name=Linux:%hostname% address=%hostname%\n";
close $h;

#### generate ncrtagent.conf

#### generate cert file.
my $conf = "$CONFDIR/agenttype_windows.openssl.conf";
my $cert = "$CONFDIR/agenttype_windows.cert.pem";
my $key  = "$CONFDIR/agenttype_windows.key.pem";
if( -f $conf && ! -f $cert && ! -f $key ){
	system "openssl req -x509 -nodes -days 3650 -newkey rsa:2048"
		. " -config $conf"
		. " -subj '/CN=ncrtagent_windows'"
		. " -outform PEM -out $cert -keyout $key";
}


