#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
if( open my $f, '<', "$CONFDIR/ncrtbuild.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		die unless m"^(\w+)=(.*)$";
		$ncrtconf{$1} = $2;
	}
	close $f;
}

#### load ncrt masters conf.
my @ncrtmasters;
if( open my $f, '<', "$CONFDIR/ncrtmasters.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		push @ncrtmasters, $_;
	}
	close $f;
}

#### load website targets
my @vhosts;
my $f = "$CONFDIR/hosttype/virtual.virtualhosts";
if( open my $h, '<', $f ){
	while( <$h> ){
		chomp;
		next if m"^\s*(#|$)";
		die "$f:$.: illegal format, stopped" unless m"^([-.\w]+)$";
		push @websites, $1;
	}
	close $h;
}

#### append hosts info.
if( open my $f, '>>', "$WORKDIR/hosts" ){
	foreach my $h ( @vhosts ){
		print $f "$h	virtual\n";
	}
	close $f;
}



