#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load service conf.
my $f = "$CONFDIR/indirect/ltsv.conf";
open my $h, '<', $f or do {
	die "$f: cannot open, stopped";
};
my $curr_vhost;
my $curr_vservice;
my %vhost2vservices;
my @backend;
while( <$h> ){
        chomp;
        next if m"^\s*(#|$)";
        if    ( m"^===\s+([-\w]+)\s+([-\w]+)\s+===$" ){
		$curr_vhost = $1;
		$curr_vservice = $2;
                $vhost2vservices{$curr_vhost}->{$curr_vservice} = 1;
        }elsif( m"^===\s+(\S+)\s+(\S+)\s+===$" ){
		$curr_vhost = undef;
		$curr_vservice = undef;
        }elsif( m"^backend=(.*)$" ){
		next unless defined $curr_vhost;
		next unless defined $curr_vservice;
		push @backend, [$curr_vhost, $curr_vservice, $1];
        }elsif( m"^\w+=.*$" ){
                # nothing to do
        }else{
                die "$f:$.: illegal format, stopped";
        }
}
close $h;

#### append service info.
my $f = "$WORKDIR/measurements";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "ltsv	indirect\n";
close $h;

#### append conf info.
my $f = "$WORKDIR/plugin2type2pluginconf2format";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
print $h "ltsv	indirect	ltsv.conf	default\n";
close $h;

#### append service mapping
my $f = "$WORKDIR/monitoredhost2service2measurement";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};

while( my ($vhost, $vservices) = each %vhost2vservices ){
	foreach my $vservice ( sort keys %$vservices ){
		my $options = $$vservices{$vservice};
		print $h "$vhost	$vservice	ltsv\n";
	}
}
close $h;

#### append service mapping
my $f = "$WORKDIR/pseudohost2service2backendhost";
open my $h, '>>', $f or do {
	die "$f: cannot open, stopped";
};
foreach my $i ( @backend ){
	my ($pseudohost, $service, $backendhost) = @$i;
	print $h "$pseudohost $service $backendhost\n";
}
close $h;

exit 0;


