#!/usr/bin/perl

use strict;

our $TOOLHOME;
BEGIN {
	$0 =~ m"^(.*)/";
	$TOOLHOME = ` cd "$1/.." && pwd || echo . `;
	chomp $TOOLHOME;
}

use lib "$TOOLHOME/plugins";
use ncrtmaster_alertqueue;

use strict;
use Carp::Always;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

####

my $min = int( time / 60 ) % 5;

mkdir_or_die "$WORKDIR/aq_event";
mkdir_or_die "$WORKDIR/aq_active";
mkdir_or_die "$WORKDIR/aq_inactive";
mkdir_or_die "$WORKDIR/aq_web";
mkdir_or_die "$WORKDIR/aq_mail";
mkdir_or_die "$WORKDIR/aq_slack";
system_or_die "$0.eventq update    $CONFDIR $WORKDIR";
#system_or_die "$0.session  open    $CONFDIR $WORKDIR";
#system_or_die "$0.web      open    $CONFDIR $WORKDIR";
#system_or_die "$0.mail     open    $CONFDIR $WORKDIR";
#system_or_die "$0.slack    open    $CONFDIR $WORKDIR";
#system_or_die "$0.session  rename  $CONFDIR $WORKDIR" if $min == 1;
#system_or_die "$0.web      rename  $CONFDIR $WORKDIR" if $min == 1;
#system_or_die "$0.slack    rename  $CONFDIR $WORKDIR" if $min == 1;
#system_or_die "$0.session  close   $CONFDIR $WORKDIR" if $min == 2;
#system_or_die "$0.web      close   $CONFDIR $WORKDIR" if $min == 2;
#system_or_die "$0.mail     close   $CONFDIR $WORKDIR" if $min == 2;
#system_or_die "$0.slack    close   $CONFDIR $WORKDIR" if $min == 2;
system_or_die "$0.eventq  cleanup  $CONFDIR $WORKDIR" if $min == 3;
#system_or_die "$0.session  cleanup $CONFDIR $WORKDIR" if $min == 3;
#system_or_die "$0.web      cleanup $CONFDIR $WORKDIR" if $min == 3;
exit 0;


