#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
if( open my $f, '<', "$CONFDIR/ncrtbuild.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		die unless m"^(\w+)=(.*)$";
		$ncrtconf{$1} = $2;
	}
	close $f;
}

#### load linux conf.
my %targets;
if( open my $f, '<', "$CONFDIR/hosttype/linux.hosts" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		die unless m"^([-.\w]+)$";
		$targets{$1} = 1;
	}
	close $f;
}

#### append hosts info.
if( open my $f, '>>', "$WORKDIR/hosts" ){
	while( my ($k, $v) = each %targets ){
		print $f "$k	linux\n";
	}
	close $f;
}

#### append hosttype info.
if( open my $f, '>>', "$WORKDIR/hosttypes" ){
	print $f "linux	display_name=Linux:%hostname% address=%hostname%\n";
	close $f;
}


