#!/usr/bin/perl

use strict;

if( @ARGV < 2 ){
	print "usage: % $0 CONFDIR WORKDIR\n";
	exit 1;
}

our $CONFDIR = $ARGV[0];
our $WORKDIR = $ARGV[1];

#### load global conf.
my %ncrtconf;
if( open my $f, '<', "$CONFDIR/ncrtbuild.conf" ){
	while( <$f> ){
		chomp;
		next if m"^\s*(#|$)";
		die unless m"^(\w+)=(.*)$";
		$ncrtconf{$1} = $2;
	}
	close $f;
}

#### load linuxhosts.
my %targets;
if( open my $f, '<', "$WORKDIR/hosts" ){
	while( <$f> ){
		chomp;
		my ($host, $hosttype) = split m"\s+";
		next unless $hosttype =~ m"^(linux)$";
		$targets{$host} = 1;
	}
	close $f;
}

#### append service info.
if( open my $h, '>>', "$WORKDIR/services" ){
	print $h "proc	agent	display_name=\"Process\"\n";
	close $h;
}

#### append conf info.
if( open my $f, '>>', "$WORKDIR/service2conf" ){
	print $f "proc	agent/proc.categories\n";
	print $f "proc	agent/proc_count.rules\n";
	print $f "proc	agent/proc_elapsed.rules\n";
	close $f;
}

#### append service mapping
if( open my $h, '>>', "$WORKDIR/host2service" ){
	foreach my $i ( keys %targets ){
		print $h "$i\tproc\n";
	}
	close $h;
}




