---

- hosts: all
  vars:
    repository:
      Debian: "deb http://labs.consol.de/repo/stable/debian {{ansible_distribution_release}} main"
      Ubuntu: "deb http://labs.consol.de/repo/stable/ubuntu {{ansible_distribution_release}} main"

  tasks:
    - include_vars: "{{WORKDIR}}/vars.yml"
      tags: [ common ]
    - include: "{{TOOLHOME}}/conf/ncrtmasters_playbook.yml"
      tags: [ common ]

    #### for Debian / Ubuntu
    - name: install packages for apt-key
      apt:
        name: [ dirmngr, pynag ]
      when: "ansible_os_family == 'Debian'"
      tags: [ commoninstall ]

    - name: install packages for nrpe-ng
      apt:
        name: [ nrpe-ng ]
      when: "ansible_os_family == 'Debian'"
      tags: [ nrpe-ng ]

    ## InfluxDB (install)
    - name: install packages for influxdb
      apt:
        name: [ influxdb, influxdb-client, python-requests, python-influxdb ]
      when: "ansible_os_family == 'Debian'"
      tags: [ commoninstall ]

    ## Grafana (install)
    - name: add repository key for grafana
      apt_key:
        data: "{{ lookup('file','grafana.asc') }}"
        keyring: /etc/apt/trusted.gpg.d/grafana.gpg
      when: "ansible_os_family == 'Debian'"
      tags: [ commoninstall ]

    - name: install packages for grafana
      apt:
        name: [ grafana ]
      when: "ansible_os_family == 'Debian'"
      tags: [ commoninstall ]

    ## Naemon (install)
    - name: add repository key
      apt_key:
        data: "{{ lookup('file','naemon.asc') }}"
        keyring: /etc/apt/trusted.gpg.d/naemon.gpg
      when: "ansible_os_family == 'Debian'"
      tags: [ commoninstall ]

    - name: add naemon repository
      apt_repository:
        repo: "{{ repository[ansible_distribution] }}"
      when: "ansible_os_family == 'Debian'"
      tags: [ commoninstall ]

    - name: install naemon and dependancies
      apt:
        name:
          - naemon
          - naemon-core
          - naemon-livestatus
          - nagios-plugins
          - naemon-thruk
          - python-passlib
          - nagios-nrpe-plugin
      when: "ansible_os_family == 'Debian'"
      tags: [ commoninstall ]

    ## NCRT (install)
    - name: install naemon and dependancies
      apt:
        name:
          - libjson-xs-perl
          - libjson-pp-perl
          - libemail-sender-perl
          - libemail-mime-perl
          - libtemplate-perl
          - libstring-random-perl
          - libmime-encwords-perl
          - liburi-query-perl
      when: "ansible_os_family == 'Debian'"
      tags: [ commoninstall ]

    ## Naemon2Influx / Naemon2Influx-Grafana-Helper (install)
    - file:
        dest:    "{{item}}"
        state:   directory
        owner:   root
        group:   root
        recurse: yes
      with_items:
          - "{{NCRTMASTERHOME}}"
          - "{{NCRTMASTERHOME}}/debs"
      when: "ansible_os_family == 'Debian'"
      tags: [ commoninstall ]

    - copy:
        dest: "{{NCRTMASTERHOME}}/debs/{{item}}"
        src:  "{{TOOLHOME}}/conf/{{item}}"
      with_items:
        - "{{NAEMON2INFLUX_DEB}}"
        - "{{NAEMON2INFLUX_GRAFANA_HELPER_DEB}}"
      when: "ansible_os_family == 'Debian'"
      tags: [ commoninstall ]

    - name: install naemon2influx / naemon2influx-grafana-helper
      apt:
        deb: "{{NCRTMASTERHOME}}/debs/{{item}}"
      with_items:
        - "{{NAEMON2INFLUX_DEB}}"
        - "{{NAEMON2INFLUX_GRAFANA_HELPER_DEB}}"
      when: "ansible_os_family == 'Debian'"
      tags: [ commoninstall ]

    - name: install packages required by naemon2influx
      apt:
        name: [ libwww-perl ]
      when: "ansible_os_family == 'Debian'"
      tags: [ commoninstall ]

    #### for All Distros

    ## InfluxDB (setting)
    - name: setup influxdb database for naemon2influx
      influxdb_database:
        hostname:      "{{INFLUXDBHOST}}"
        port:          "{{INFLUXDBPORT}}"
        username:      "{{INFLUXDBADMINUSER}}"
        password:      "{{INFLUXDBADMINPASSWD}}"
        database_name: "{{INFLUXDBDATABASE}}"
      tags: [ commoninstall ]

    - name: setup influxdb user for naemon2influx
      influxdb_user:
        hostname:      "{{INFLUXDBHOST}}"
        port:          "{{INFLUXDBPORT}}"
        username:      "{{INFLUXDBADMINUSER}}"
        password:      "{{INFLUXDBADMINPASSWD}}"
        user_name:     "{{INFLUXDBUSER}}"
        user_password: "{{INFLUXDBPASSWD}}"
      tags: [ commoninstall ]

    - name: setup influxdb for naemon2influx
      shell: "influx -host {{INFLUXDBHOST}} -port {{INFLUXDBPORT}} -username {{INFLUXDBADMINUSER}} -password \"{{INFLUXDBADMINPASSWD}}\" -execute \"grant all on naemon to naemon\""
      tags: [ commoninstall ]

    ## Grafana (setting)

    ## Naemon (setting)
    - name: remove unused default settings for Nagios / Naemon
      shell: "test -f /etc/naemon/conf.d/{{item}} && mv /etc/naemon/conf.d/{{item}} /etc/naemon/conf.d/{{item}}.unused"
      failed_when: False
      with_items:
        - localhost.cfg
        - printer.cfg
        - switch.cfg
        - windows.cfg
      tags: [ common ]

    - name: setup static setting files (by NCRT) for Nagios / Naemon
      template:
        src: "{{item}}"
        dest: "/etc/naemon/conf.d/{{item}}"
      with_items:
        - ncrt_naemon2influx.cfg
        - ncrt_naemon_commands.cfg
        - ncrt_naemon_timeperiods.cfg
      notify: restart naemon
      tags: [ common ]

    - name: setup dynamic setting files (by NCRT) for Nagios / Naemon
      template:
        src: "{{WORKDIR}}/{{item}}"
        dest: "/etc/naemon/conf.d/{{item}}"
      with_items:
        - ncrt_servicetemplates.cfg
        - ncrt_services.cfg
        - ncrt_hosttemplates.cfg
        - ncrt_hosts.cfg
        - ncrt_users.cfg
        - ncrt_addresses.cfg
        - ncrt_hostgroups.cfg
        - ncrt_servicegroups.cfg
      notify: restart naemon
      tags: [ common ]

    - name: setup dynamic setting items Nagios / Naemon with naemon2influx
      lineinfile:
        dest: "/etc/naemon/naemon.cfg"
        regexp: "^{{item.key}}="
        line:   "{{item.key}}={{item.value}}"
        insertafter: EOF
      with_items:
        - key:   process_performance_data
          value: 1
        - key:   service_perfdata_file_processing_command
          value: ncrt-process-service-perfdata-naemon2influx
        - key:   service_perfdata_file_mode
          value: a
        - key:   service_perfdata_file_processing_interval
          value: 5
        - key:   service_perfdata_file_template
          value: '$TIMET$\t$HOSTNAME$\t$SERVICEDESC$\t$SERVICESTATE$\t$SERVICEPERFDATA$'
        - key:   service_perfdata_file
          value: /var/lib/naemon/service-perfdata
      notify: restart naemon
      tags: [ common ]

    ## NCRT (setting)
    - name: setup modules in ncrt master
      synchronize:
        checksum: yes
        rsync_opts: [ "-OJ", "--chown=root:root", "--exclude=/filters/" ]
        src: "{{TOOLHOME}}/ncrtmaster/"
        dest: "{{NCRTMASTERHOME}}/"
      tags: [ common ]

    - name: setup filters
      synchronize:
        checksum: yes
        rsync_opts: [ "-OJ", "--chown=root:root" ]
        src: "{{TOOLHOME}}/filters/"
        dest: "{{NCRTMASTERHOME}}/filters/"
      tags: [ common ]

    - name: setup settings in ncrt master
      synchronize:
        checksum: yes
        delete: yes
        rsync_opts: [ "-OJ", "--chown=root:root" ]
        src: "{{WORKDIR}}/ncrtmaster/{{inventory_hostname}}/"
        dest: "{{NCRTMASTERHOME}}/conf/"
      tags: [ common ]

    - name: setup gateway accessor
      template:
        mode: 0755
        src: "ncrtmaster_passthrough"
        dest: "{{NCRTMASTERHOME}}/bin/ncrtmaster_passthrough"
      tags: [ common ]

    - name: setup nrpe server cert/key
      copy:
        dest:  /etc/ssl/certs/ncrt_cert.pem
        src:   "{{TOOLHOME}}/conf/ncrt_cert.pem"
      notify: update ssl certs
      tags: [ common ]

    - name: setup ncrtmaster_alertmessenger cron
      cron:
        name: ncrtmaster_alertmessenger cron
        user: naemon
        hour:   "*"
        minute: "*"
        job: "{{NCRTMASTERHOME}}/bin/ncrtmaster_alertmessenger cron 2>> ~/.ncrt.cronerror 1>&2"
      tags: [ common ]

    ## Naemon2Influx / Naemon2Influx-Grafana-Helper (setting)
    - name: setup naemon2influx setting file
      file:
        dest: /etc/naemon/naemon2influx.cfg
        mode: 0640
        owner: naemon
        group: naemon
      notify: restart naemon
      tags: [ common ]

    - name: setup naemon2influx settings
      lineinfile:
        dest: /etc/naemon/naemon2influx.cfg
        regexp: "^{{item.key}}="
        line:   "{{item.key}}={{item.value}}"
        insertafter: EOF
      with_items:
        - key:   output
          value: "http://{{INFLUXDBHOST}}:{{INFLUXDBPORT}}"
        - key:   username
          value: "{{INFLUXDBUSER}}"
        - key:   password
          value: "{{INFLUXDBPASSWD}}"
        - key:   perfformat
          value: "time	label	label	tag=state	data"
      tags: [ common ]

    - name: setup naemon2influx-grafana-helper settings
      lineinfile:
        dest: /etc/naemon/naemon2influx-grafana-helper.conf
        regexp: "^{{item.key}}="
        line:   "{{item.key}}={{item.value}}"
        insertafter: EOF
      with_items:
        - key:   GRAFANAURL
          value: "{{GRAFANAURL}}"
        - key:   GRAFANAAPIKEY
          value: "{{GRAFANAAPIKEY}}"
        - key:   GRAFANADATASOURCE
          value: "{{GRAFANADATASOURCE}}"
      tags: [ common ]


  handlers:
    - name: update ssl certs
      shell: "update-ca-certificates -f"
      tags: [ common ]

    - name: restart naemon
      service:
        name:  naemon
        state: restarted
        use:   service
      tags: [ common ]



