---

- hosts: all
  vars:
    nrpeconfdir:
      Debian: /etc/nagios/nrpe.d
      RedHat: /etc/nrpe.d

  tasks:
    - include_vars: "{{WORKDIR}}/vars.yml"
      tags: [ common ]

    #### for Debian / Ubuntu
    - name: install packages for nrpe plugins
      apt:
        name:
          - monitoring-plugins
          - monitoring-plugins-basic
          - monitoring-plugins-common
          - monitoring-plugins-standard
      when: "ansible_os_family == 'Debian'"
      tags: [ common ]

    - name: install packages for nrpe
      apt:
        name: [ nagios-nrpe-server ]
      when: "ansible_os_family == 'Debian'"
      tags: [ nrpe ]

    - name: install packages for nrpe-ng
      apt:
        name: [ nrpe-ng ]
      when: "ansible_os_family == 'Debian'"
      tags: [ nrpe-ng ]

    #### for RedHat / CentOS
    - name: install packages for nrpe plugins
      yum:
        name:
          - nagios-plugins-nrpe
      when: "ansible_os_family == 'RedHat'"
      tags: [ common ]

    - name: install packages for nrpe
      yum:
        name: [ nrpe ]
      when: "ansible_os_family == 'RedHat'"
      tags: [ nrpe ]

    - file:
        path: /opt
        state: directory
        owner: root
        group: root
      tags: [ common ]

    - name: setup modules in ncrt agent
      synchronize:
        checksum: yes
        rsync_opts: [ "-OJ", "--chown=root:root" ]
        src: "{{TOOLHOME}}/ncrtagent/"
        dest: "{{NCRTAGENTHOME}}/"
      tags: [ common ]

    - name: setup nrpe server cert/key
      copy:
        dest:  "/etc/nagios/{{item}}"
        src:   "{{TOOLHOME}}/conf/{{item}}"
      with_items: [ ncrt_cert.pem, ncrt_key.pem ]
      tags: [ nrpe-ng, nrpetls ]

    - name: setup nrpe server
      lineinfile:
        dest:   /etc/nagios/nrpe.cfg
        regexp: "^{{item.key}}="
        line:   "{{item.key}}={{item.value}}"
        insertafter: EOF
      with_items:
        - { key: dont_blame_nrpe, value: 1 }
      notify: restart nrpe
      tags: [ nrpe ]

    - name: setup nrpe server tls
      lineinfile:
        dest:   /etc/nagios/nrpe.cfg
        regexp: "^{{item.key}}="
        line:   "{{item.key}}={{item.value}}"
        insertafter: EOF
      with_items:
        - { key: ssl_cert_file, value: /etc/nagios/ncrt_cert.pem }
        - { key: ssl_privatekey_file, value: /etc/nagios/ncrt_key.pem }
      notify: restart nrpe
      tags: [ nrpetls ]

    - name: setup nrpe-ng server
      lineinfile:
        dest:   /etc/nagios/nrpe-ng.cfg
        regexp: "^{{item.key}}="
        line:   "{{item.key}}={{item.value}}"
        insertafter: EOF
      with_items:
        - { key: ssl_cert_file, value: /etc/nagios/ncrt_cert.pem }
        - { key: ssl_key_file, value: /etc/nagios/ncrt_key.pem }
        - { key: dont_blame_nrpe, value: 1 }
      notify: restart nrpe
      tags: [ nrpe-ng ]

    - name: setup settings in ncrt agent
      synchronize:
        checksum: yes
        delete: yes
        rsync_opts: [ "-OJ", "--chown=root:root" ]
        src: "{{WORKDIR}}/ncrtagent/{{ansible_hostname}}/"
        dest: "{{NCRTAGENTHOME}}/conf/"
      notify: restart nrpe
      tags: [ common ]

    - name: setup settings in ncrt agent
      template:
        src: ncrt_nrpe_commands.cfg
        dest: "{{ nrpeconfdir[ansible_os_family] }}/ncrt_nrpe_commands.cfg"
      notify: restart nrpe
      tags: [ common ]

  handlers:
    - name: update ssl certs
      shell: "update-ca-certificates -f"
      tags: [ common ]

    - name: restart nrpe
      service:
        name:  nrpe
        state: restarted
      tags: [ nrpe ]

    - name: restart nrpe
      service:
        name:  nrpe-ng
        state: restarted
      tags: [ nrpe-ng ]







