---

- hosts: all
  tasks:
    - name: include variables
      include_vars: "{{WORKDIR}}/vars.yml"
      tags: [ common ]

    - name: import playbook
      import_playbook: "{{TOOLHOME}}/plugins/ncrtbuild_agenttype_{{item}}.yml"
      when: "ansible_os_family in ['RedHat', 'Debian']"
      with_items:
        - linux

    - name: include customize tasks
      import_tasks: "{{TOOLHOME}}/conf/ncrtagents_playbook.yml"
      tags: [ common ]


