#!/bin/bash

if [ $# -lt 4 ] ; then
	echo "usage: % $0 SERVICE VHOST VSERVICE HOST"
	exit 1
fi

SERVICE=$1
VHOST=$2
VSERVICE=$3
HOST=$4

{% if AGENTPACKAGE == "nrpe-ng" %}
/usr/lib/nagios/plugins/check_nrpe_ng -C /etc/nagios/check_nrpe_ng.cfg -H $HOST -c ncrtagent_passthrough -a $SERVICE $VHOST $VSERVICE
{% elif AGENTPACKAGE == "nrpe" %}
/usr/lib/nagios/plugins/check_nrpe {% if NRPETLS == "no" %}-n{% endif %} -p {{NRPEPORT}} -H $HOST -c ncrtagent_passthrough -a $SERVICE $VHOST $VSERVICE
{% endif %}

