#!/bin/bash

if [ $# -lt 4 ] ; then
	echo "usage: % $0 PROXYHOST MEASURE HOST SERVICE"
	exit 1
fi

PROXYHOST=$1
MEASURE=$2
HOST=$3
SERVICE=$4

{% if AGENTPACKAGE == "nrpe-ng" %}
/usr/lib/nagios/plugins/check_nrpe_ng -C /etc/nagios/check_nrpe_ng.cfg -H $PROXYHOST -c ncrtagent_passthrough -a $MEASURE $HOST $SERVICE
{% elif AGENTPACKAGE == "nrpe" %}
/usr/lib/nagios/plugins/check_nrpe {% if NRPETLS == "no" %}-n{% endif %} -p {{NRPEPORT}} -H $PROXYHOST -c ncrtagent_passthrough -a $MEASURE $HOST $SERVICE
{% endif %}

